version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        env_file:
            - ./environments/.env.dev
    database:
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_dev