version: '3'
services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '5000:5000'
        env_file:
            - ./environments/.env.prod
        depends_on:
            - database
    database:
        restart: always
        image: postgres:12.0-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_prod