version: '3'
services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        env_file:
            - ./.env.dev
        depends_on:
            - database
    database:
        image: postgres:12.0-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_dev