version: '3'
services:
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.prod
        expose:
            - 5000
        env_file:
            - ./environments/.env.prod
    database:
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres_prod
    nginx:
        build: ./nginx
        ports:
            - 8000:80
        depends_on:
            - api